export default function InventoryPage() {
  return (
    <div>
      <div>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci totam rem temporibus! At, voluptas eos! Ducimus et doloribus ipsum. Nostrum iure excepturi illo voluptate obcaecati tempore eaque modi nesciunt doloribus.</p>
      </div>
    </div>
  )
}
